apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maintenancer
  namespace: webapl5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maintenancer
subjects:
- kind: ServiceAccount
  name: maintenancer1
  namespace: webapl5
  