apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
    protocol: TCP      
  selector:
    app: postgres-sts
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres-sts
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sts
  template:
    metadata:
      labels:
        app: postgres-sts
    spec:
      #terminationGracePeriodSeconds: 0
      #nodeSelector:
      #  role: worker-node
      containers:
      - name: postgres
        image: postgres:12.9-alpine3.14
        ports:
        - containerPort: 5432
          name: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: postgres_password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: postgres_user
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: postgres_db
      - name: util
        image: maho/pg-util:0.1
        command: ["tail", "-f", "/dev/null"]        
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: postgres_password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: postgres_user
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: postgres_db
                
        ports:
        - name: pg-service
          containerPort: 6379
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql
          subPath: data
        #- name: backup
        #  mountPath: /backup
        #  subPath: data          
        #- name: pg-config
        #  mountPath: /etc/postgres
      #volumes:
      #- name: pg-config
      #  configMap:
      #    name: pg-config
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csi-rbd-sc
      ##storageClassName: csi-cephfs-sc
      ##storageClassName: rook-ceph-block
      volumeMode: Filesystem
      resources:
        requests:
          storage: 2Gi
  #- metadata:
  #    name: backup
  #  spec:
  #    accessModes: [ "ReadWriteOnce" ]
  #    storageClassName: csi-rbd-sc
  #    volumeMode: Filesystem
  #    resources:
  #      requests:
  #        storage: 2Gi
         
