apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - nodePort: 30379
      port: 6379
  selector:
    app: redis
    tier: backend


