---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: cephfs
  userKey: AQAtoqhhtNSLGhAABYUN6hBT3VdQfKKcPr39DQ==

  # Required for dynamically provisioned volumes
  adminID: cephfs
  adminKey: AQAtoqhhtNSLGhAABYUN6hBT3VdQfKKcPr39DQ==
