apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/maho/helloworld-python
          env:
            - name: TARGET
              value: "Python Sample v1"
