apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session2
  template:
    metadata:
      labels:
        app: session2
    spec:
      containers:
        - image: 'maho/session-test:1.1'
          name: session2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: session-svc2
spec:
  selector:
    app: session2
  type: LoadBalancer
  ports:
    - name: http  
      port: 9080
      targetPort: 80
     
