apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-group
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: dev-group
  
