apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user
  namespace: dev-webapl7
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev-user-1
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev-user-2
  
