apiVersion: v1
kind: Service
metadata:
  name: webapl5
  labels:
    app: webapl5
    service: webapl5
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: webapl5
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapl5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapl5
      version: v1
  template:
    metadata:
      labels:
        app: webapl5
        version: v1
    spec:
      containers:
      - name: java
        image: maho/webapl5:0.1
        imagePullPolicy: Always        
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
          failureThreshold: 5