---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: csi-rbd-sc 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-sc 
---
## デプロイメント 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.10-focal
        args: ["--config", "/etc/mongo/mongod.conf"]
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-auth
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-auth
                key: password
        volumeMounts:
          - name: mongodb-data
            mountPath: /var/lib/mongodb
          - name: mongodb-log
            mountPath: /var/log/mongodb/
          - name: mongodb-config
            mountPath: /etc/mongo
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data
          readOnly: false
      - name: mongodb-log
        persistentVolumeClaim:
          claimName: mongodb-log
          readOnly: false
      - name: mongodb-config
        configMap:
          name: mongodb-config
---
## サービス
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
