FROM ubuntu:20.04

RUN apt update && apt upgrade -y
RUN apt -y install gnupg2 wget vim ca-certificates gnupg postgresql-client
#RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
#RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
#RUN apt update && apt -y install postgresql-14





