apiVersion: v1
kind: Pod
metadata:
  name: filesystem-1
spec:
  affinity:
    #nodeAffinity:
    #  requiredDuringSchedulingIgnoredDuringExecution:
    #    nodeSelectorTerms:
    #    - matchExpressions:
    #      - key: role
    #        operator: In
    #        values:
    #        - mds-node
    #topologySpreadConstraints:
    #tolerations:
    #- key: mds-node
    #  operator: Exists
    #podAffinity:
    podAntiAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
       - labelSelector:
           matchExpressions:
           - key: app
             operator: In
             values:
             - rook-ceph-mds
         # topologyKey: kubernetes.io/hostname will place MDS across different hosts
         topologyKey: kubernetes.io/hostname
       preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 100
         podAffinityTerm:
           labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - rook-ceph-mds
           # topologyKey: */zone can be used to spread MDS across different AZ
           # Use <topologyKey: failure-domain.beta.kubernetes.io/zone> in k8s cluster if your cluster is v1.16 or lower
           # Use <topologyKey: topology.kubernetes.io/zone>  in k8s cluster is v1.17 or upper
           topologyKey: topology.kubernetes.io/zone

  containers:
  - name: with-node-affinity
    image: docker.io/nginx
