apiVersion: batch/v1
kind: Job
metadata:
  name: crdb-init
  labels:
    app: my-crdb
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        image: cockroachdb/cockroach:v21.2.5
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "init"
          - "--insecure"
          - "--host=my-crdb.crdb:26258"
      restartPolicy: OnFailure
