apiVersion: v1
kind: Service
metadata:
  name: my-crdb-lb
  namespace: crdb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: my-crdb
    app.kubernetes.io/name: cockroachdb
  ports:
  - name: grpc
    port: 26258
    protocol: TCP
    targetPort: 26258
    nodePort: 32258    
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32080    
  - name: sql
    port: 26257
    protocol: TCP
    targetPort: 26257
    nodePort: 32257
    